services:
  - type: web
    name: website-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: website_db_u8wx
          property: connectionString
